[package]
name = "janus_client"
description = "Client for Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_client"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
derivative.workspace = true
http.workspace = true
itertools.workspace = true
janus_core.workspace = true
janus_messages.workspace = true
prio.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json"] }
thiserror.workspace = true
tokio.workspace = true
tracing = "0.1.40"
url = "2.5.0"

[dev-dependencies]
assert_matches.workspace = true
hex-literal = "0.4.1"
janus_core = { workspace = true, features = ["test-util"]}
mockito = "1.4.0"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
