[package]
name = "janus_server"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
rust-version = "1.58"

[dependencies]
anyhow = "1"
bytes = "1.1.0"
chrono = "0.4"
deadpool-postgres = "0.10.1"
derivative = "2"
hex = "0.4.3"
hpke = { version = "0.8.0", features = ["default", "std"] }
http = "0.2.6"
lazy_static = "1"
num_enum = "0.5.6"
postgres-types = { version = "0.2.2", features = ["derive"] }
prio = "0.7.0"
rand = "0.8"
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.16.20"
testcontainers = "0.12.0"
thiserror = "1.0"
tokio = { version = "^1.9", features = ["full"] }
tokio-postgres = { version = "0.7.5", features = ["with-chrono-0_4"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.9", features = ["std", "env-filter"] }
url = "2.2.2"
warp = { version = "^0.3", features = ["tls"] }

[dev-dependencies]
assert_matches = "1"
hyper = "0.14.17"
mockito = "0.31.0"
