[package]
name = "janus_server"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
rust-version = "1.58"

[dependencies]
anyhow = "1"
hex = "0.4.3"
hpke = { version = "0.8.0", features = ["default", "std"] }
lazy_static = "1"
num_enum = "0.5.6"
prio = "0.7.0"
rand = "0.8"
ring = "0.16.20"
thiserror = "1.0"
