version: 2

updates:
  # Manage dependencies on the main branch
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: prio
        update-types:
          - version-update:semver-minor
    groups:
      serde:
        patterns:
          - serde
          - serde_*
      tracing:
        patterns:
          - tracing
          - tracing-*
      opentelemetry:
        patterns:
          - opentelemetry
          - opentelemetry-*
          - tonic
      trillium:
        patterns:
          - trillium
          - trillium-*
      kube:
        patterns:
          - kube
          - k8s-openapi
      postgres:
        patterns:
          - tokio-postgres
          - postgres-*
      deadpool:
        patterns:
          - deadpool
          - deadpool-*
      error-handling:
        patterns:
          - thiserror
          - anyhow
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    groups:
      docker:
        patterns:
          - docker/*
          - crazymax/ghaction-github-runtime
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    ignore:
      - dependency-name: "postgres"

  # Manage dependencies on the `release/0.subscriber-01` branch
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.subscriber-01"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: prio
        update-types:
          - version-update:semver-minor
    groups:
      serde:
        patterns:
          - serde
          - serde_*
      tracing:
        patterns:
          - tracing
          - tracing-*
      opentelemetry:
        patterns:
          - opentelemetry
          - opentelemetry-*
          - tonic
      trillium:
        patterns:
          - trillium
          - trillium-*
      kube:
        patterns:
          - kube
          - k8s-openapi
      postgres:
        patterns:
          - tokio-postgres
          - postgres-*
      deadpool:
        patterns:
          - deadpool
          - deadpool-*
      error-handling:
        patterns:
          - thiserror
          - anyhow
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.subscriber-01"
    groups:
      docker:
        patterns:
          - docker/*
          - crazymax/ghaction-github-runtime
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.subscriber-01"
    ignore:
      - dependency-name: "postgres"

  # Manage dependencies on the `release/0.5` branch
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.5"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: prio
        update-types:
          - version-update:semver-minor
    groups:
      serde:
        patterns:
          - serde
          - serde_*
      tracing:
        patterns:
          - tracing
          - tracing-*
      opentelemetry:
        patterns:
          - opentelemetry
          - opentelemetry-*
          - tonic
      trillium:
        patterns:
          - trillium
          - trillium-*
      kube:
        patterns:
          - kube
          - k8s-openapi
      postgres:
        patterns:
          - tokio-postgres
          - postgres-*
      deadpool:
        patterns:
          - deadpool
          - deadpool-*
      error-handling:
        patterns:
          - thiserror
          - anyhow
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.5"
    groups:
      docker:
        patterns:
          - docker/*
          - crazymax/ghaction-github-runtime
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.5"
    ignore:
      - dependency-name: "postgres"
