version: 2

updates:
  # Manage dependencies on the main branch
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 20
    groups:
      serde:
        patterns:
          - serde
          - serde_*
      tracing:
        patterns:
          - tracing
          - tracing-*
      opentelemetry:
        patterns:
          - opentelemetry
          - opentelemetry-*
          - tonic
      trillium:
        patterns:
          - trillium
          - trillium-*
      kube:
        patterns:
          - kube
          - k8s-openapi
      postgres:
        patterns:
          - tokio-postgres
          - postgres-*
      error-handling:
        patterns:
          - thiserror
          - anyhow
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  # Manage dependencies on the `release/0.subscriber-01` branch
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.subscriber-01"
    open-pull-requests-limit: 20
    groups:
      serde:
        patterns:
          - serde
          - serde_*
      tracing:
        patterns:
          - tracing
          - tracing-*
      opentelemetry:
        patterns:
          - opentelemetry
          - opentelemetry-*
          - tonic
      trillium:
        patterns:
          - trillium
          - trillium-*
      kube:
        patterns:
          - kube
          - k8s-openapi
      postgres:
        patterns:
          - tokio-postgres
          - postgres-*
      error-handling:
        patterns:
          - thiserror
          - anyhow
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.subscriber-01"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.subscriber-01"

  # Manage dependencies on the `release/0.5` branch
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.5"
    open-pull-requests-limit: 20
    groups:
      serde:
        patterns:
          - serde
          - serde_*
      tracing:
        patterns:
          - tracing
          - tracing-*
      opentelemetry:
        patterns:
          - opentelemetry
          - opentelemetry-*
          - tonic
      trillium:
        patterns:
          - trillium
          - trillium-*
      kube:
        patterns:
          - kube
          - k8s-openapi
      postgres:
        patterns:
          - tokio-postgres
          - postgres-*
      error-handling:
        patterns:
          - thiserror
          - anyhow
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.5"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/0.5"
