[workspace]
members = [
    "aggregator",
    "aggregator_api",
    "aggregator_core",
    "client",
    "collector",
    "core",
    "integration_tests",
    "interop_binaries",
    "messages",
    "tools",
    "xtask",
]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://divviup.org"
license = "MPL-2.0"
repository = "https://github.com/divviup/janus"
rust-version = "1.71.0"
version = "0.6.5"

[workspace.dependencies]
anyhow = "1"
assert_matches = "1"
base64 = "0.21.5"
# Disable default features to disable compatibility with the old `time` crate, and we also don't
# (yet) need other default features.
# https://docs.rs/chrono/latest/chrono/#duration
chrono = { version = "0.4", default-features = false }
derivative = "2.2.0"
itertools = "0.11"
janus_aggregator = { version = "0.6", path = "aggregator" }
janus_aggregator_api = { version = "0.6", path = "aggregator_api" }
janus_aggregator_core = { version = "0.6", path = "aggregator_core" }
janus_client = { version = "0.6", path = "client" }
janus_collector = { version = "0.6", path = "collector" }
janus_core = { version = "0.6", path = "core" }
janus_integration_tests = { version = "0.6", path = "integration_tests" }
janus_interop_binaries = { version = "0.6", path = "interop_binaries" }
janus_messages = { version = "0.6", path = "messages" }
k8s-openapi = { version = "0.20.0", features = ["v1_24"] }  # keep this version in sync with what is referenced by the indirect dependency via `kube`
kube = { version = "0.87.1", default-features = false, features = ["client", "rustls-tls"] }
opentelemetry = { version = "0.21", features = ["metrics"] }
opentelemetry_sdk = { version = "0.21", features = ["metrics"] }
prio = { version = "0.15.3", features = ["multithreaded", "experimental"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_test = "1.0.175"
serde_yaml = "0.9.27"
rand = "0.8"
rstest = "0.18.2"
testcontainers = "0.15.0"
thiserror = "1.0"
tokio = { version = "1.34", features = ["full", "tracing"] }
trillium = "0.2.11"
trillium-api = { version = "0.2.0-rc.7", default-features = false }
trillium-caching-headers = "0.2.1"
trillium-head = "0.2.0"
trillium-opentelemetry = "0.3.0"
trillium-router = "0.3.5"
trillium-testing = "0.5.0"
trillium-tokio = "0.3.2"

[profile.ci]
# Disabling debug info improves build speeds & reduces build artifact sizes, which helps CI caching.
inherits = "dev"
debug = 0

[profile.small]
# We define a profile intended to minimize the eventual binary size, while still allowing for
# relatively fast compilation. It is intended for use in size-constrained testing scenarios, e.g.
# building a binary artifact that ends up embedded in another binary.
inherits = "dev"
opt-level = "z"   # Optimize for size.
debug = false     # Do not generate debug info.
strip = true      # Strip symbols from binary.
