[workspace]
members = [
    "aggregator",
    "aggregator_api",
    "aggregator_core",
    "client",
    "collector",
    "core",
    "integration_tests",
    "interop_binaries",
    "messages",
    "tools",
    "xtask",
]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://divviup.org"
license = "MPL-2.0"
repository = "https://github.com/divviup/janus"
rust-version = "1.73.0"
version = "0.7.7"

[workspace.dependencies]
anyhow = "1"
assert_matches = "1"
async-trait = "0.1"
backoff = "0.4.0"
base64 = "0.22.0"
bytes = "1"
cfg-if = "1.0.0"
# Disable default features to disable compatibility with the old `time` crate, and we also don't
# (yet) need other default features.
# https://docs.rs/chrono/latest/chrono/#duration
chrono = { version = "0.4.38", default-features = false }
clap = { version = "4.5.3", features = ["cargo", "derive", "env"] }
console-subscriber = "0.2.0"
deadpool = "0.11.2"
deadpool-postgres = "0.13.0"
derivative = "2.2.0"
divviup-client = "0.2"
fixed = "1.27"
fixed-macro = "1.1.1"
futures = "0.3.30"
git-version = "0.3.9"
hex = "0.4.3"
hex-literal = "0.4.1"
hpke-dispatch = "0.5.1"
http = "1.1"
http-api-problem = "0.58.0"
itertools = "0.12"
janus_aggregator = { version = "0.7.7", path = "aggregator" }
janus_aggregator_api = { version = "0.7.7", path = "aggregator_api" }
janus_aggregator_core = { version = "0.7.7", path = "aggregator_core" }
janus_client = { version = "0.7.7", path = "client" }
janus_collector = { version = "0.7.7", path = "collector" }
janus_core = { version = "0.7.7", path = "core" }
janus_interop_binaries = { version = "0.7.7", path = "interop_binaries" }
janus_messages = { version = "0.7.7", path = "messages" }
k8s-openapi = { version = "0.21.0", features = ["v1_26"] }  # keep this version in sync with what is referenced by the indirect dependency via `kube`
kube = { version = "0.90.0", default-features = false, features = ["client", "rustls-tls"] }
mockito = "1.4.0"
num_enum = "0.7.2"
opentelemetry = { version = "0.22", features = ["metrics"] }
opentelemetry-otlp = "0.15"
opentelemetry-prometheus = "0.15"
opentelemetry_sdk = { version = "0.22", features = ["metrics"] }
opentelemetry-semantic-conventions = "0.14"
pem = "3"
postgres-protocol = "0.6.6"
postgres-types = "0.2.6"
pretty_assertions = "1.4.0"
# Disable default features so that individual workspace crates can choose to
# re-enable them
prio = { version = "0.16.3", default-features = false, features = ["experimental"] }
prometheus = "0.13.3"
querystring = "1.1.0"
rand = "0.8"
rayon = "1.10.0"
reqwest = { version = "0.12.4", default-features = false, features = ["rustls-tls"] }
regex = "1.10.4"
retry-after = "0.4.0"
ring = "0.17.8"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
rustc_version = "0.4.0"
rustls = "0.23.5"
rustls-pemfile = "2.1.2"
sec1 = "0.7"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
serde_test = "1.0.175"
serde_urlencoded = "0.7.1"
serde_yaml = "0.9.34"
signal-hook = "0.3.17"
signal-hook-tokio = "0.3.1"
sqlx = "0.7.4"
stopper = "0.2.7"
tempfile = "3.10.1"
testcontainers = "0.16.5"
thiserror = "1.0"
tracing = "0.1.40"
tracing-chrome = "0.7.2"
tracing-log = "0.2.0"
tracing-opentelemetry = "0.23"
tracing-stackdriver = "0.10.0"
tracing-subscriber = "0.3"
tokio = { version = "1.37", features = ["full", "tracing"] }
tokio-postgres = "0.7.10"
tokio-postgres-rustls = "0.12.0"
tokio-stream = "0.1.15"
trillium = "0.2.19"
trillium-api = { version = "0.2.0-rc.11", default-features = false }
trillium-caching-headers = "0.2.3"
trillium-head = "0.2.2"
trillium-macros = "0.0.6"
trillium-opentelemetry = "0.7.0"
trillium-prometheus = "0.1.0"
trillium-proxy = { version = "0.5.4", default-features = false }
trillium-router = "0.3.6"
trillium-rustls = "0.7.0"
trillium-testing = "0.6.1"
trillium-tokio = "0.4.0"
trycmd = "0.15.1"
url = { version = "2.5.0", features = ["serde"] }
uuid = { version = "1.8.0", features = ["v4"] }
wait-timeout = "0.2.0"
zstd = "0.13"

[profile.ci]
# Disabling debug info improves build speeds & reduces build artifact sizes, which helps CI caching.
inherits = "dev"
debug = 0
# Incremental compilation is also disabled via environment variable by the Swatinem/rust-cache action.
incremental = false

[profile.small]
# We define a profile intended to minimize the eventual binary size, while still allowing for
# relatively fast compilation. It is intended for use in size-constrained testing scenarios.
inherits = "dev"
opt-level = "z"   # Optimize for size.
debug = false     # Do not generate debug info.
strip = true      # Strip symbols from binary.
