[workspace]
members = [
    "aggregator",
    "build_script_utils",
    "client",
    "collector",
    "core",
    "integration_tests",
    "interop_binaries",
    "messages",
]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://divviup.org"
license = "MPL-2.0"
repository = "https://github.com/divviup/janus"
rust-version = "1.64.0"
version = "0.2.0"

[profile.dev]
# Disabling debug info improves build speeds & reduces
# build artifact sizes (which helps CI caching).
debug = 0

[profile.small]
# We define a profile intended to minimize the eventual binary size, while still allowing for
# relatively fast compilation. It is intended for use in size-constrained testing scenarios, e.g.
# building a binary artifact that ends up embedded in another binary.
inherits = "dev"
opt-level = "z"   # Optimize for size.
debug = false     # Do not generate debug info.
strip = true      # Strip symbols from binary.
