[package]
name = "janus_core"
description = "Core type definitions and utilities used in various components of Janus."
documentation = "https://docs.rs/janus_core"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
fpvec_bounded_l2 = ["prio/experimental"]
test-util = [
    "dep:assert_matches",
    "dep:lazy_static",
    "dep:kube",
    "dep:k8s-openapi",
    "dep:serde_json",
    "dep:tempfile",
    "dep:testcontainers",
    "dep:tracing-log",
    "dep:tracing-subscriber",
    "tokio/macros",
    "tokio/sync"
]

[dependencies]
assert_matches = { version = "1", optional = true }
backoff = { version = "0.4.0", features = ["tokio"] }
base64 = "0.21.0"
chrono = { workspace = true, features = ["clock"] }
derivative = "2.2.0"
futures = "0.3.27"
hex = "0.4"
hpke-dispatch = "0.5.0"
http-api-problem = "0.56.0"
janus_messages.workspace = true
kube = { workspace = true, optional = true, features = ["rustls-tls"] }
k8s-openapi = { workspace = true, optional = true }
lazy_static = { version = "1", optional = true }
prio.workspace = true
rand = "0.8"
reqwest = { version = "0.11.15", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.16.20"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = { version = "1.0.95", optional = true }
serde_yaml = "0.9.19"
tempfile = { version = "3", optional = true }
testcontainers = { version = "0.14", optional = true }
thiserror = "1.0"
tokio = { version = "1.26", features = ["macros", "net", "rt"] }
tracing = "0.1.37"
tracing-log = { version = "0.1.3", optional = true }
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"], optional = true }

[dev-dependencies]
fixed = "1.23"
hex = { version = "0.4", features = ["serde"] }  # ensure this remains compatible with the non-dev dependency
janus_core = { path = ".", features = ["test-util"] }
# Enable `kube`'s `openssl-tls` feature (which takes precedence over the
# `rustls-tls` feature when creating a default client) to work around rustls's
# lack of support for connecting to servers by IP addresses, which affects many
# Kubernetes clusters.
kube = { workspace = true, features = ["openssl-tls"] }
mockito = "1.0.0"
serde_test = "1.0.158"
url = "2.3.1"
