[package]
name = "janus_core"
description = "Core type definitions and utilities used in various components of Janus."
documentation = "https://docs.rs/janus_core"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-util = [
    "dep:assert_matches",
    "dep:lazy_static",
    "dep:kube",
    "dep:k8s-openapi",
    "dep:serde_json",
    "dep:tempfile",
    "dep:testcontainers",
    "dep:tracing-log",
    "dep:tracing-subscriber",
    "tokio/macros",
    "tokio/sync"
]

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
base64 = "0.21.0"
chrono = "0.4"
derivative = "2.2.0"
futures = "0.3.28"
hex = "0.4"
hpke-dispatch = "0.5.0"
http-api-problem = "0.56.0"
janus_messages = { version = "0.2", path = "../messages" }
kube = { workspace = true, optional = true, features = ["rustls-tls"] }
k8s-openapi = { workspace = true, optional = true }
prio = { version = "0.10.0", features = ["multithreaded"] }
rand = "0.8"
reqwest = { version = "0.11.16", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.16.20"
serde = { version = "1.0.160", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.27", features = ["macros", "net", "rt"] }
tracing = "0.1.37"

# Dependencies required only if feature "test-util" is enabled
assert_matches = { version = "1", optional = true }
lazy_static = { version = "1", optional = true }
serde_json = { version = "1.0.96", optional = true }
tempfile = { version = "3", optional = true }
testcontainers = { version = "0.14", optional = true }
tracing-log = { version = "0.1.3", optional = true }
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"], optional = true }

[dev-dependencies]
hex = { version = "0.4", features = ["serde"] }  # ensure this remains compatible with the non-dev dependency
janus_core = { path = ".", features = ["test-util"] }
kube.workspace = true
mockito = "1.0.2"
serde_test = "1.0.160"
url = "2.3.1"
