[package]
name = "janus_aggregator_core"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
test-util = [
    "dep:hex",
    "dep:lazy_static",
    "dep:testcontainers",
    "janus_core/test-util",
    "janus_messages/test-util",
]

[dependencies]
async-trait = "0.1"
anyhow = "1"
backoff = { version = "0.4.0", features = ["tokio"] }
base64 = "0.21.0"
bytes = "1.4.0"
chrono = "0.4"
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
deadpool-postgres = "0.10.5"
derivative = "2.2.0"
futures = "0.3.26"
hex = { version = "0.4.3", features = ["serde"], optional = true }
http = "0.2.9"
http-api-problem = "0.56.0"
hyper = "0.14.24"
janus_core.workspace = true
janus_messages.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
lazy_static = { version = "1", optional = true }
opentelemetry = { version = "0.18", features = ["metrics", "rt-tokio"] }
postgres-protocol = "0.6.4"
postgres-types = { version = "0.2.4", features = ["derive", "array-impls"] }
prio.workspace = true
rand = { version = "0.8", features = ["min_const_gen"] }
regex = "1"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.16.20"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_yaml = "0.9.17"
testcontainers = { version = "0.14.0", optional = true }
thiserror = "1.0"
tokio = { version = "1.25", features = ["full", "tracing"] }
tokio-postgres = { version = "0.7.7", features = ["with-chrono-0_4", "with-serde_json-1", "with-uuid-1", "array-impls"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.0", features = ["v4"] }

[dev-dependencies]
assert_matches = "1"
hyper = "0.14.24"
janus_aggregator_core = { workspace = true, features = ["test-util"] }
janus_core = { workspace = true, features = ["test-util"] }
serde_test = "1.0.152"
tempfile = "3.4.0"
tokio = { version = "1", features = ["test-util"] }  # ensure this remains compatible with the non-dev dependency

[build-dependencies]
rustc_version = "0.4.0"
