[package]
name = "janus_integration_tests"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
in-cluster = ["dep:k8s-openapi", "dep:kube"]

[dependencies]
anyhow.workspace = true
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.22.1"
futures = "0.3.30"
hex = "0.4"
http.workspace = true
janus_aggregator = { workspace = true, features = ["test-util"] }
janus_aggregator_core = { workspace = true, features = ["test-util"] }
janus_client.workspace = true
janus_collector.workspace = true
janus_core = { workspace = true, features = ["test-util"] }
janus_interop_binaries = { workspace = true, features = ["testcontainer"] }
janus_messages.workspace = true
k8s-openapi = { workspace = true, optional = true }
kube = { workspace = true, optional = true }
prio.workspace = true
rand = "0.8"
reqwest.workspace = true
serde.workspace = true
serde_json = "1.0.117"
testcontainers.workspace = true
tokio.workspace = true
url = { version = "2.5.2", features = ["serde"] }

[dev-dependencies]
itertools.workspace = true
janus_collector = { workspace = true, features = ["test-util"] }
tempfile = "3"
