[package]
name = "janus_integration_tests"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
kube-openssl = ["kube/openssl-tls"]

[dependencies]
anyhow = "1"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.13.1"
futures = "0.3.25"
hex = "0.4"
janus_aggregator = { path = "../aggregator", features = ["test-util"] }
janus_client = { path = "../client" }
janus_core = { path = "../core", features = ["test-util"] }
janus_interop_binaries = { path = "../interop_binaries", features = ["testcontainer"] }
janus_messages = { path = "../messages" }
k8s-openapi.workspace = true
kube.workspace = true
portpicker = "0.1"
prio = { version = "0.10.0", features = ["multithreaded"] }
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.89"
testcontainers = "0.14.0"
tokio = { version = "1", features = ["full", "tracing"] }
tracing = "0.1.37"
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
http = "0.2"
itertools = "0.10"
janus_collector = { path = "../collector", features = ["test-util"] }
tempfile = "3"
