[package]
name = "janus_integration_tests"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
in-cluster = ["dep:k8s-openapi", "dep:kube"]
testcontainer = ["janus_interop_binaries/testcontainer"]

[dependencies]
anyhow.workspace = true
backoff = { version = "0.4", features = ["tokio"] }
base64.workspace = true
divviup-client = { git = "https://github.com/divviup/divviup-api", features = ["admin"], tag = "0.0.30" }
futures = "0.3.28"
hex = "0.4"
http = "0.2"
itertools.workspace = true
janus_aggregator = { workspace = true, features = ["test-util"] }
janus_aggregator_core = { workspace = true, features = ["test-util"] }
janus_client.workspace = true
janus_collector.workspace = true
janus_core = { workspace = true, features = ["test-util"] }
janus_interop_binaries = { workspace = true, features = ["test-util"] }
janus_messages.workspace = true
k8s-openapi = { workspace = true, optional = true }
kube = { workspace = true, optional = true }
prio.workspace = true
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde.workspace = true
serde_json = "1.0.108"
testcontainers.workspace = true
tokio.workspace = true
url = { version = "2.4.1", features = ["serde"] }
trillium-tokio.workspace = true

[dev-dependencies]
janus_collector = { workspace = true, features = ["test-util"] }
tempfile = "3"
