[package]
name = "janus_integration_tests"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
in-cluster = ["dep:k8s-openapi", "dep:kube"]
testcontainer = ["janus_interop_binaries/testcontainer"]
in-cluster-rate-limits = []

[dependencies]
anyhow.workspace = true
assert_matches.workspace = true
backoff = { version = "0.4", features = ["tokio"] }
base64.workspace = true
clap.workspace = true
futures = "0.3.30"
hex = "0.4"
http = "0.2"
itertools.workspace = true
janus_aggregator = { workspace = true, features = ["test-util"] }
janus_aggregator_core = { workspace = true, features = ["test-util"] }
janus_client.workspace = true
janus_collector.workspace = true
janus_core = { workspace = true, features = ["test-util"] }
janus_interop_binaries = { workspace = true, features = ["test-util"] }
janus_messages.workspace = true
k8s-openapi = { workspace = true, optional = true }
kube = { workspace = true, optional = true }
prio = { workspace = true, features = ["test-util"] }
rand.workspace = true
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde.workspace = true
serde_json = "1.0.114"
testcontainers.workspace = true
tokio.workspace = true
trillium-tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
divviup-client = { version = "0.1", features = ["admin"] }
janus_collector = { workspace = true, features = ["test-util"] }
rstest.workspace = true
tempfile = "3"
trillium-rustls.workspace = true
