# This configuration file is used in the janus_interop_aggregator container
# image. It is tuned for very low aggregation latency, to speed up integration
# tests, and is not intended for production use.
database:
  url: postgres://postgres@127.0.0.1:5432/postgres
  check_schema_version: false
health_check_listen_address: 0.0.0.0:8002
logging_config:
  force_json_output: true
job_discovery_interval_s: 2
max_concurrent_job_workers: 10
worker_lease_clock_skew_allowance_s: 1
worker_lease_duration_s: 10
maximum_attempts_before_failure: 3
batch_aggregation_shard_count: 32
task_counter_shard_count: 32
