[package]
name = "janus_messages"
description = "Distributed Aggregation Protocol message definitions used in Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_messages"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-util = []

[dependencies]
anyhow.workspace = true
base64 = "0.21.0"
derivative = "2.2.0"
hex = "0.4"
num_enum = "0.6.1"
# We can't pull prio in from the workspace because that would enable default features, and we do not
# want prio/crypto-dependencies
prio = { version = "0.12.1", default-features = false }
rand = "0.8"
serde = { version = "1.0.162", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1"
serde_test = "1.0.160"
