[package]
name = "interop_binaries"
version = "0.1.11"
edition = "2021"
license = "MPL-2.0"
rust-version = "1.63"
publish = false

[features]
test-util = [
    "dep:hex",
    "dep:futures",
    "dep:lazy_static",
    "dep:regex",
    "dep:zstd",
]
testcontainer = [
    "dep:build_script_utils",
    "dep:testcontainers",
    "test-util",
]

[dependencies]
anyhow = "1"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.13.0"
clap = "3.2.21"
futures = { version = "0.3.24", optional = true }
hex = { version = "0.4", optional = true }
lazy_static = { version = "1", optional = true }
janus_client = { path = "../janus_client" }
janus_collector = { path = "../janus_collector" }
janus_core = { path = "../janus_core" }
janus_server = { path = "../janus_server" }
opentelemetry = { version = "0.17", features = ["metrics"] }
prio = { version = "0.8.2", features = ["multithreaded"] }
rand = "0.8"
regex = { version = "1", optional = true }
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls"] }
ring = "0.16.20"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
testcontainers = { version = "0.14", optional = true }
tokio = { version = "1.21", features = ["full", "tracing"] }
tracing = "0.1.36"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
url = { version = "2.3.0", features = ["serde"] }
warp = "0.3"
zstd = { version = "0.11", optional = true }

[dev-dependencies]
interop_binaries = { path = ".", features = ["testcontainer"] }
janus_core = { path = "../janus_core", features = ["test-util"] }
reqwest = { version = "0.11.4", default-features = false, features = ["json"] }
testcontainers = "0.14.0"

[build-dependencies]
build_script_utils = { path = "../build_script_utils", optional = true }
