[package]
name = "janus_aggregator"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
fpvec_bounded_l2 = ["dep:fixed", "janus_core/fpvec_bounded_l2"]
tokio-console = ["dep:console-subscriber"]
otlp = [
    "dep:opentelemetry-otlp",
    "dep:opentelemetry-semantic-conventions",
    "dep:opentelemetry_sdk",
    "dep:tracing-opentelemetry",
]
prometheus = [
    "dep:opentelemetry-prometheus",
    "dep:opentelemetry_sdk",
    "dep:prometheus",
    "dep:trillium-prometheus",
]
test-util = [
    "janus_core/test-util",
    "janus_messages/test-util",
    "dep:assert_matches",
    "dep:hex",
    "dep:testcontainers",
    "dep:trillium-testing",
]

[dependencies]
anyhow.workspace = true
assert_matches = { workspace = true, optional = true }
async-trait = "0.1"
backoff = { version = "0.4.0", features = ["tokio"] }
base64.workspace = true
bytes = "1.5.0"
chrono.workspace = true
clap.workspace = true
console-subscriber = { version = "0.2.0", optional = true }
deadpool = { version = "0.10.0", features = ["rt_tokio_1"] }
deadpool-postgres = "0.12.1"
derivative.workspace = true
fixed = { version = "1.25", optional = true }
futures = "0.3.30"
git-version = "0.3.9"
hex = { version = "0.4.3", features = ["serde"], optional = true }
http = "0.2.11"
http-api-problem = "0.57.0"
itertools.workspace = true
janus_aggregator_api.workspace = true
janus_aggregator_core.workspace = true
janus_core.workspace = true
janus_messages.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp = { version = "0.14", optional = true, features = ["metrics"] }
opentelemetry-prometheus = { version = "0.14", optional = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"], optional = true }
opentelemetry-semantic-conventions = { version = "0.13", optional = true }
postgres-protocol = "0.6.6"
postgres-types = { version = "0.2.6", features = ["derive", "array-impls"] }
prio.workspace = true
prometheus = { version = "0.13.3", optional = true }
rand = { workspace = true, features = ["min_const_gen"] }
regex = "1"
reqwest = { version = "0.11.24", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.17.7"
routefinder = "0.5.4"
rustls = "0.22.2"
rustls-pemfile = "2.0.0"
serde.workspace = true
serde_json.workspace = true
serde_urlencoded = "0.7.1"
serde_yaml.workspace = true
signal-hook = "0.3.17"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
testcontainers = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4", "with-serde_json-1", "with-uuid-1", "array-impls"] }
tokio-postgres-rustls = "0.11.1"
tracing = "0.1.40"
tracing-chrome = "0.7.1"
tracing-log = "0.2.0"
tracing-opentelemetry = { version = "0.22", optional = true }
tracing-stackdriver = "0.9.0"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt", "json"] }
trillium.workspace = true
trillium-api.workspace = true
trillium-caching-headers.workspace = true
trillium-head.workspace = true
trillium-opentelemetry.workspace = true
trillium-prometheus = { version = "0.1.0", optional = true }
trillium-router.workspace = true
trillium-testing = { workspace = true, optional = true }
trillium-tokio.workspace = true
url.workspace = true

[dev-dependencies]
janus_aggregator = { path = ".", features = ["fpvec_bounded_l2", "test-util"] }
janus_aggregator_core = { workspace = true, features = ["test-util"] }
mockito = "1.2.0"
opentelemetry_sdk = { workspace = true, features = ["testing"] }
rstest.workspace = true
tempfile = "3.10.0"
tokio = { version = "1", features = ["test-util"] } # ensure this remains compatible with the non-dev dependency
trillium-testing.workspace = true
trycmd = "0.14.21"
wait-timeout = "0.2.0"

[build-dependencies]
rustc_version = "0.4.0"
