[package]
name = "janus_tools"
description = "Command line tools associated with Janus, the server powering ISRG's Divvi Up."
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
fpvec_bounded_l2 = ["dep:fixed", "janus_collector/fpvec_bounded_l2", "prio/experimental"]

[dependencies]
anyhow = "1"
base64.workspace = true
clap.workspace = true
derivative.workspace = true
fixed = { version = "1.27", optional = true }
janus_collector.workspace = true
janus_core.workspace = true
janus_messages.workspace = true
prio.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
url = "2.5.0"

[dev-dependencies]
assert_matches.workspace = true
cfg-if = "1.0.0"
janus_core = { workspace = true, features = ["test-util"] }
tempfile = "3.10.1"
trycmd = "0.15.0"
