[package]
name = "janus_aggregator_api"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1"
base64 = "0.21.0"
janus_aggregator_core.workspace = true
janus_core.workspace = true
janus_messages.workspace = true
opentelemetry = "0.18"
querystring = "1.1.0"
rand = { version = "0.8", features = ["min_const_gen"] }
ring = "0.16.20"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_test = "1.0.160"
tracing = "0.1.37"
trillium.workspace = true
trillium-api.workspace = true
trillium-macros = "0.0.4"
trillium-opentelemetry.workspace = true
trillium-router.workspace = true
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
futures = "0.3.28"
janus_aggregator_core = { workspace = true, features = ["test-util"] }
tokio = "1.27"
trillium-testing = { workspace = true, features = ["tokio"] }
