[package]
name = "janus_collector"
description = "Collector for Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_collector"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
fpvec_bounded_l2 = ["dep:fixed", "dep:fixed-macro", "janus_core/fpvec_bounded_l2", "prio/experimental"]
test-util = []

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
chrono.workspace = true
derivative.workspace = true
janus_core.workspace = true
janus_messages.workspace = true
fixed = { version = "1.24", optional = true }
fixed-macro = { version = "1.1.1", optional = true }
prio.workspace = true
rand = { version = "0.8", features = ["min_const_gen"] }
reqwest = { version = "0.11.22", default-features = false, features = ["rustls-tls", "json"] }
retry-after = "0.3.1"
thiserror.workspace = true
tokio.workspace = true
tracing = "0.1.40"
url = "2.4.1"

[dev-dependencies]
assert_matches.workspace = true
janus_collector = { path = ".", features = ["fpvec_bounded_l2", "test-util"] }
janus_core = { workspace = true, features = ["fpvec_bounded_l2", "test-util"] }
mockito = "1.2.0"
rand = "0.8"
