[package]
name = "janus_collector"
description = "Collector for Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_collector"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
test-util = []

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
chrono.workspace = true
derivative = "2.2.0"
http-api-problem = "0.57.0"
janus_core.workspace = true
janus_messages.workspace = true
prio.workspace = true
rand = { version = "0.8", features = ["min_const_gen"] }
reqwest = { version = "0.11.19", default-features = false, features = ["rustls-tls", "json"] }
retry-after = "0.3.1"
thiserror.workspace = true
tokio.workspace = true
tracing = "0.1.37"
url = "2.4.0"

[dev-dependencies]
assert_matches = "1"
janus_collector = { path = ".", features = ["test-util"] }
janus_core = { workspace = true, features = ["test-util"] }
mockito = "1.1.0"
rand = "0.8"
