name: ci-build

on:
  push:
    branches: [ main, release/** ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  janus_server_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: lint
      run: cargo fmt --message-format human -- --check
    - name: clippy
      run: cargo clippy --all-targets -- -D warnings
    - name: check, all features
      run: cargo check --all-features
    - name: build
      run: cargo build --verbose
    - name: test
      env:
        RUST_LOG: trace
      run: cargo test --verbose
  janus_server_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - env:
        DOCKER_BUILDKIT: 1
      run: docker build --tag janus_server .
    - env:
        DOCKER_BUILDKIT: 1
      run: docker build --tag janus_aggregation_job_creator --build-arg BINARY=aggregation_job_creator .
    - run: docker run --rm janus_server --help
    - run: docker run --rm janus_aggregation_job_creator --help
