name: ci-build

on:
  push:
    branches: [ main, release/** ]
  pull_request:
  workflow_dispatch:

jobs:
  janus_build:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
      RUSTFLAGS: "-D warnings"
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go toolchain
      uses: actions/setup-go@v3
    - name: Install Kind
      # We should always make sure that the `kind` CLI we install is from the
      # same release as the node image version used by
      # `janus_core::test_util::kubernetes::EphemeralCluster`
      run: go install sigs.k8s.io/kind@v0.14.0
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo test --no-run --locked
    - name: Test
      run: cargo test
  
  janus_lints:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
      JANUS_INTEROP_CONTAINER: skip
      RUSTDOCFLAGS: "-D warnings"
      RUSTFLAGS: "-D warnings"
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: clippy, rustfmt
    - name: Format
      run: cargo fmt --message-format human -- --check
    - name: Clippy
      run: cargo clippy --workspace --all-targets
    - name: Document
      run: cargo doc --workspace

  janus_docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v3
    - run: docker build --tag janus_server .
    - run: docker build --tag janus_aggregation_job_creator --build-arg BINARY=aggregation_job_creator .
    - run: docker build --tag janus_aggregation_job_driver --build-arg BINARY=aggregation_job_driver .
    - run: docker build --tag janus_collect_job_driver --build-arg BINARY=collect_job_driver .
    - run: docker build --tag janus_cli --build-arg BINARY=janus_cli .
    - run: docker run --rm janus_server --help
    - run: docker run --rm janus_aggregation_job_creator --help
    - run: docker run --rm janus_aggregation_job_driver --help
    - run: docker run --rm janus_collect_job_driver --help
    - run: docker run --rm janus_cli --help

  janus_interop_docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v3
    - run: docker build --tag janus_interop_client --build-arg BINARY=janus_interop_client -f Dockerfile.interop .
    - run: docker build --tag janus_interop_aggregator -f Dockerfile.interop_aggregator .
    - run: docker build --tag janus_interop_collector --build-arg BINARY=janus_interop_collector -f Dockerfile.interop .
