name: ci-build

on:
  push:
    branches: [ main, release/** ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  janus_server_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Kind
      # We should always make sure that the `kind` CLI we install is from the
      # same release as the node image version used by
      # `janus_core::test_util::kubernetes::EphemeralCluster`
      run: go install sigs.k8s.io/kind@v0.14.0
    - name: Install Miniflare
      # Miniflare is used in support of Daphne integration tests.
      run: npm install --location=global miniflare
    - name: lint
      run: cargo fmt --message-format human -- --check
    - name: clippy
      run: cargo clippy --workspace --all-targets -- -D warnings
    - name: check, all features
      run: cargo check --all-features
    - name: build
      run: cargo build --verbose
    - name: test
      env:
        RUST_LOG: trace
      # set PATH to ensure we use go binaries installed above
      run: PATH=$(go env GOPATH)/bin:$PATH cargo test --verbose
    - name: document
      env:
        CARGO_TARGET_DIR: "target/doc-deny"
        RUSTDOCFLAGS: "-Dwarnings"
      run: cargo doc
  janus_server_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - env:
        DOCKER_BUILDKIT: 1
      run: docker build --tag janus_server .
    - env:
        DOCKER_BUILDKIT: 1
      run: docker build --tag janus_aggregation_job_creator --build-arg BINARY=aggregation_job_creator .
    - env:
        DOCKER_BUILDKIT: 1
      run: docker build --tag janus_aggregation_job_driver --build-arg BINARY=aggregation_job_driver .
    - env:
        DOCKER_BUILDKIT: 1
      run: docker build --tag janus_collect_job_driver --build-arg BINARY=collect_job_driver .
    - run: docker run --rm janus_server --help
    - run: docker run --rm janus_aggregation_job_creator --help
    - run: docker run --rm janus_aggregation_job_driver --help
    - run: docker run --rm janus_collect_job_driver --help
