name: ci-migrations

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    # paths:
      # - "db/**"
  workflow_dispatch:

jobs:
  janus_migrations:
    runs-on: ubuntu-latest
    env:
      BASE_SHA: "${{ github.event.pull_request.base.sha }}"
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: "./.github/actions/validate-migrations"
      with:
        from: "${{ github.event.pull_request.base.sha }}"
