name: publish-crates

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.DIVVIUP_AUTOMATON_JANUS_CRATES_IO_TOKEN }}

jobs:
  crate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # We retry crate publishing to allow the newly published janus_core to be
    # visible on crates.io when we get around to publishing janus_client and
    # janus_collector.
    - name: "Publish janus_core"
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        polling_interval_seconds: 30
        command: cargo publish -p janus_core
    - name: "Publish janus_client"
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        polling_interval_seconds: 30
        command: cargo publish -p janus_client
    - name: "Publish janus_collector"
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        polling_interval_seconds: 30
        command: cargo publish -p janus_collector
