name: yank-crates

on:
  workflow_dispatch:
    inputs:
      version:
        description: crate version to yank from crates.io
        required: true
        type: string

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.DIVVIUP_AUTOMATON_JANUS_CRATES_IO_TOKEN }}

jobs:
  yank:
    strategy:
      matrix:
        crate:
          - janus_messages
          - janus_core
          - janus_client
          - janus_collector
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: "Yank"
      run: cargo yank --version ${{ inputs.version }} ${{ matrix.crate }}
